### ISSUE TITLE
Building with OCamlbuild fails

### ISSUE THREAD

**Issue by BreD1810** [herd/herdtools7#113]
Herdtools builds fine with Dune, but breaks with Ocamlbuild:
![image](https://user-images.githubusercontent.com/32489229/99066125-5e2dff80-25a0-11eb-9fe4-f6f95aa90f16.png)

OCaml version: 4.11.1
Ocamlbuild version: 0.14.0
Dune version: 2.7.1

**Comment by BreD1810** [comment]
I believe the Option module also requires Ocaml >= 4.08, where as herdtools requires OCaml >= 4.05
(https://caml.inria.fr/pub/docs/manual-ocaml/libref/Option.html)

**Comment by maranget** [comment]
You are right, thanks for reporting this problem. Corrected by commit c783ed8376b08beba2a6718710d9f46ecd12c639.

**Comment by BreD1810** [comment]
Fixed, thanks!
