### ISSUE TITLE
An example for RC11 litmus test

### ISSUE THREAD

**Issue by fresheed** [herd/herdtools7#13]
Could you please provide an example on how to write litmus test for RC11 memory model? 
Trying to run any test included in doc/ folder, I get following error:
```
$ herd7 -c11 -statelessrc11 true doc/tst-arm/LB.litmus 
File "doc/tst-arm/LB.litmus": annotation RMW not found

```

How should I define/include this relation and what is a syntax for RC11 tests in general?

**Comment by maranget** [comment]
The test has to be written in C11 as for instance the test at the end. Also consider that herd7 distribution features a rc11.cat model, which is our reference for the RC11 memory model, being quite close to the model description from the article. By contrast `-statelessrc11 true` is an experimental implementation.

In a word, we advise to run RC11 tests as follows:
```
$ herd7 -c11 -cat rc11.cat ....
```
 An here is an example of a test:
```
C LB+porlxrlxs

{}

P0 (atomic_int* y,atomic_int* x) {
  atomic_int r0 = atomic_load_explicit(x,memory_order_relaxed);
  atomic_store_explicit(y,1,memory_order_relaxed);
}

P1 (atomic_int* y,atomic_int* x) {
  atomic_int r0 = atomic_load_explicit(y,memory_order_relaxed);
  atomic_store_explicit(x,1,memory_order_relaxed);
}

exists
(0:r0=1 /\ 1:r0=1)
```

**Comment by fresheed** [comment]
Thank you!
