### ISSUE TITLE
klitmus7 regression since KVM branch merge

### ISSUE THREAD

**Issue by akiyks** [herd/herdtools7#164]
C flavour of litmus tests stopped working.
old-master works fine.

A simple C flavour litmus test:

```
C C-2+2W+o-o+o-o

{}

P0(int *x0, int *x1)
{
	WRITE_ONCE(*x0, 1);
	WRITE_ONCE(*x1, 2);
}

P1(int *x0, int *x1)
{
	WRITE_ONCE(*x1, 1);
	WRITE_ONCE(*x0, 2);
}

exists (x0=1 /\ x1=1)
```

ends up in the error:

`klitmus7 -o /tmp C-2+2W+o-o+o-o.litmus
File "C-2+2W+o-o+o-o.litmus" exception File "litmus/CArch_litmus.ml", line 75, characters 27-33: Assertion failed
Fatal error: exception File "litmus/CArch_litmus.ml", line 75, characters 27-33: Assertion failed`

**Comment by maranget** [comment]
Hello Akira,

Sorry for the inconvenience, I am working on this.

Meanwhile, if in emergency, branch old-master should still be working.

Sorry again, I should have been more cautious.

—Luc

**Comment by maranget** [comment]
`klitmus7` on branch master should be working now. Sorry again for having been so in a hurry to update master.

 --Luc

**Comment by akiyks** [comment]
Hi Luc,

Thanks for the quick fix.
Tested the updated master and klitmus7 works fine now.

Closing this issue.

Thanks, Akira
