### ISSUE TITLE
C11: Missing mo for nonatomic stores to atomic locations

### ISSUE THREAD

**Issue by HampusAdolfsson** [herd/herdtools7#191]
Consider the following c11 test:
```
C Test
{
}
void P0(atomic_int *x) {
	*x = 1;
	int n = atomic_load_explicit(x, memory_order_relaxed);
}
exists(0:n=0)
```
Herd allows `0:n=0` from the following execution:
![_T_Wnaa0_Raqa0](https://user-images.githubusercontent.com/15944368/110604756-b52b9600-8188-11eb-8d21-fbbb07c5e47f.png)
in which `b` reads from `ix`, even though `ix` is not a visible side effect of `b`.

It seems to me like there is a `mo` missing between `ix` and `a`, because `c11_cos.cat` does not consider nonatomic stores to be part of `mo` for atomic locations. The rc11 model works fine, but this affects all the other c11 models.

Please let me know if I have understood this correctly, and if this is something you consider worth fixing.
Thanks

**Comment by maranget** [comment]
I cannot answer your without further reference, what should be the effect of mixing non-atomic and atomic operations on locations of atomic types?

**Comment by maranget** [comment]
I have checked gcc and llvm behaviour on your example. Il seems that both compilers interpret *x=1 as atomic_store(x,1) (_i.e._ as a SC atomic store). Is this documented somewhere?

**Comment by HampusAdolfsson** [comment]
You're right, there doesn't seem to be a way to do this with popular compilers, so maybe this is only interesting from an academic standpoint. I am asking because I was confused that herd and Cppmem gave different results for this test.

I believe a nonatomic write to an atomic location works the same as any nonatomic write, *except* it needs to be included in the `mo` for that location. The coherence axiom should ensure that reads always read the last written value, but that doesn't work here since `a` is not in `mo`.

I am basing this on [Batty et al's model](https://www.cl.cam.ac.uk/~pes20/cpp/popl085ap-sewell.pdf); they define the `coherent_modification_order` predicate to include *all* writes to atomic locations, but herd only uses atomic writes and initialization events:
https://github.com/herd/herdtools7/blob/36547cd435c5598cdab9a2d8f543fe91f84f4708/herd/libdir/c11_cos.cat#L7

It seems `rc11.cat` inserts `mo` for all nonatomic writes even to nonatomic locations, so maybe that is an option.

**Comment by maranget** [comment]
Herd C11 models (except RC11) are transcriptions of the [old .cat models](http://multicore.doc.ic.ac.uk/overhauling/) by Mark Batty, Alastair F. Donaldson, and John Wickerson from their paper  Overhauling SC atomics in C11 and OpenCL, as explained by [this (inconspicuous) file](https://github.com/herd/herdtools7/blob/master/herd/libdir/C11-README.txt) from herd distribution.

This alone may explain differences with cppmen that, if I am not wrong, implements Batty et al.'s original C11 model (the POPL16 paper you  refer to).

Looking briefly at Batty et al. .cat files, (see top of file [c11_base.cat)](http://multicore.doc.ic.ac.uk/overhauling/c11_base.cat), I think my transcription follows the original model intent. Hence I'd tend not to change anything here.

**Comment by HampusAdolfsson** [comment]
Alright, that makes sense.

Thank you for your time!
