### ISSUE TITLE
Another litmus test that runs on old herd but fails on herd7

### ISSUE THREAD

**Issue by AndriyLin** [herd/herdtools7#2]
Hi,

While trying multiple C11 tests, I found another test from <http://multicore.doc.ic.ac.uk/overhauling/C11/cppmem_unsequencedrace.litmus>:

```
C cppmem_unsequenced_race

{
[x] = 2;
[y] = 0;
}

// This litmus test is ported from an example distributed
// with the CppMem tool. Original is available online at:
// http://svr-pes20-cppmem.cl.cam.ac.uk/cppmem/index.html

P0 (int* x, int* y) {
  *y = (*x == (*x = 3));
}

exists
()
```

which will complain:

```
line 13, characters 18-19: unexpected '=' (in prog)
```

in herd7 but runs with old version herd.

**Comment by maranget** [comment]
Hi,

Hum, for herd7, stores cannot occur in expression position.
I admit this is a significant shortcoming.

However, fixing this would mean important changes, and would be of marginal
interest. I will not fix this now.

--Luc
