### ISSUE TITLE
Litmus operating system check doesn't recognise macOS correctly

### ISSUE THREAD

**Issue by MattWindsor91** [herd/herdtools7#21]
The check for macOS in [litmus/runUtils.ml](https://github.com/herd/herdtools7/blob/43cfe8db2959559c1c34dfa13cdff965e952897d/litmus/runUtils.ml#L73) does so by testing the presence of the file `/mach_kernel`.  This file [hasn't existed since OSX Yosemite](https://discussions.apple.com/thread/6735137) and as such the check erroneously reports modern macOS as Linux.  This then leads to:

```
Fatal error: open_in failed: /proc/cpuinfo: No such file or directory
```

I have a quick-ish fix that replaces the file test with a scrape on the output of `uname -s`, which I'll post as a PRQ, but there might be a more principled way of doing it that I hadn't thought of!

**Comment by maranget** [comment]
Hi thank your for reporting the issue, I'll merge-in your pull request.
