### ISSUE TITLE
C11 fetch_sub performs an add, not a sub

### ISSUE THREAD

**Issue by HampusAdolfsson** [herd/herdtools7#212]
`atomic_fetch_sub` behaves the same as `atomic_fetch_add`, i.e. it performs an addition instead of a subtraction. Seems like there is a 'typo' here:
https://github.com/herd/herdtools7/blob/87ac9e59996d457f665a0a5a6790e88b30adb5ab/lib/CLexer.mll#L53-L54

**Comment by maranget** [comment]
Obviously a bug, thanks for reporting it.

**Comment by maranget** [comment]
The bug i now corrected, thanks again for the report.
