### ISSUE TITLE
catalogue/hsa all.sh and ALL.sh confuse case-insensitive filesystems

### ISSUE THREAD

**Issue by MattWindsor91** [herd/herdtools7#22]
On case-insensitive filesystems (such as the default macOS one =(), the presence of  [catalogue/hsa/ALL.sh](https://github.com/herd/herdtools7/blob/master/catalogue/hsa/ALL.sh) / [catalogue/hsa/all.sh](https://github.com/herd/herdtools7/blob/master/catalogue/hsa/all.sh)
and
[catalogue/hsa/papier-tests/ALL.sh](https://github.com/herd/herdtools7/blob/master/catalogue/hsa/papier-tests/ALL.sh) / [catalogue/hsa/papier-tests/all.sh](https://github.com/herd/herdtools7/blob/master/catalogue/hsa/papier-tests/all.sh) causes several problems: generally `git` only clones one of them at a time and constantly thinks that it has uncommitted changes changing it from the other one.

I haven't used any of the scripts/content in the `catalogue` directory, so I'm not sure if there are any other issues that this causes, or what the best solution would be?

**Comment by maranget** [comment]
Hi,

The best solution is to rename files so as to avoid such clashes, and I'll do it.

That said, it is high time one should adopt modern, case-sensitive, file systems. I am always puzzled that some still survive.

In any case you will probably not use anything from the ``catalogue`` and ``herd-www`` directories, which are part of the github source only, not of releases. Indeed, those are the sources of the (still experimental) [web interface](http://diy.inria.fr/www/).
.
