### ISSUE TITLE
How is "klitmus7 -carch PPC" supposed to work?

### ISSUE THREAD

**Issue by akiyks** [herd/herdtools7#232]
Hi, 
I tried the "-carch PPC" option to klitmus7, but unable to generate proper code for PowerPC (ppc64le).

By manually replacing the code (for x86) in generated code:

```
inline static tb_t read_timebase(void) {
  uint32_t a,d; ;
  asm __volatile__ ("rdtsc" : "=a" (a), "=d" (d)) ;
  return ((tb_t)a) | (((tb_t)d)<<32);
}
```
with the one found in litmus/libdir/_ppc/timebase64.c:
```
inline static tb_t read_timebase(void) {
  tb_t r;
  asm __volatile__ ("mftb %[r1]" :[r1] "=r" (r) : : "memory");
  return r;
}
```
, "make" on ppc64le succeeds and the kernel module runs as expected.

How does the "-carch" option supposed to work?

Thanks, Akira

**Comment by maranget** [comment]
Hi @akiyks , -carch should work as you have tried. That is, `-carch PPC` should select the code you have inserted manually in klitmus7 output. In other words you have discovered a bug. Thanks for reporting it.

**Comment by maranget** [comment]
Hi @akiyks. I have fixed the problem by PR #233. Notice that if you use option `-carch PPC`, 64bit PPC is assumed. Not using the `-carch` option should work for 32bit PPC.

I'll merge the PR tomorrow if you have no objections.

Thanks again for your report.

**Comment by akiyks** [comment]
Hi Luc,

So, without the -carch option, does klitmus7 generate arch-independent code now?
I've confirmed that "-carch PPC" works as expected.

-- Thanks, Akira

**Comment by maranget** [comment]
> Hi Luc,
> 
> So, without the -carch option, does klitmus7 generate arch-independent code now?

Your are correct, if your test is in C (klitmus7 now accept tests written in X86_64 assembly). That said if there exist a possibility to read "time stamp counters" in a portable way, one can get rid of assembly code.

**Comment by akiyks** [comment]
Now that PR #233 has been merged, I'm closing this issue.

Thanks, again.
-- Akira

**Comment by maranget** [comment]
> On 6 May 2021, at 11:31, Akira Yokosawa ***@***.***> wrote:
> 
> 
> Now that PR #233 has been merged, I'm closing this issue.
> 
> Thanks, again.
> — Akira

Thanks, your contribution is precious.

—Luc
