### ISSUE TITLE
[Minor] Some annotations missing

### ISSUE THREAD

**Issue by iziva** [herd/herdtools7#242]
Hello ! 

I noticed some unlisted annotations when running:
`diy7 -arch AArch64 -show annotations`
`X.w0 X.h0 X.h2 XL.w0 XL.h0 XL.h2 XA.w0 XA.h0 XA.h2 XAL.w0 XAL.h0 XAL.h2 L.w0 L.h0 L.h2 Q.w0 Q.h0 Q.h2 A.w0 A.h0 A.h2 N1.w0 N1.h0 N1.h2 N2.w0 N2.h0 N2.h2 N3.w0 N3.h0 N3.h2 N4.w0 N4.h0 N4.h2 w0 h0 h2 X XL XA XAL L Q A N1 N2 N3 N4`

More specifically, the annotation 'T' (meaning "Tag"), which I found in non-mixed MTE litmus tests for AArch64, is not listed. The same goes for the 'P' (meaning "Plain") annotation.
These are seen, for example, in: `catalogue/aarch64-MTE/tests/MP+dmb.stPT+addr.litmus`

Also, when looking at examples such as:
- `catalogue/aarch64-mixed/tests/MP+dmb.syb0b1+datab1b1-rfib1h0.litmus`
- `catalogue/aarch64-mixed/tests/MP+dmb.syw0w4+dataw4w4-rfiw4q0.litmus`
we can see that there are b0, b1 (from the first litmus test), and w4 and q0 (from the second one) missing too.

Just posting it here so this observation is known to you guys.
Have a good day!

**Comment by maranget** [comment]
Hi,

To use annotation `T` (and see it with option `-show annotations`), use option `-variant memtag`. The same applies to the complete mixed-size annotations with option `-variant mixed`.

You are right to point out that annotation `P` is not shown. This was not known to us. Thanks.
