### ISSUE TITLE
Multiple definition error

### ISSUE THREAD

**Issue by jfariasf** [herd/herdtools7#25]
Hello,

I just tried to compile it and received this error:

> File "herd/archExtra_herd.ml", line 82, characters 2-42:
> Error: Multiple definition of the type name loc_global.
>        Names must be unique in a given structure or signature.

It was working before the last updates. Thanks.

OS: Kubuntu 19.10
GNU Make 4.2.1

**Comment by maranget** [comment]
Hello,

This compatibility issue is corrected by commit https://github.com/herd/herdtools7/commit/f2e53327f3838d1ecd0005c924aa073a072b3056.

Beware that compatibility is ensured only from ocaml 4.02.0.

Thanks for your report,
