### ISSUE TITLE
Soundness issue with C atomic_compare_exchange_strong

### ISSUE THREAD

**Issue by vafeiadis** [herd/herdtools7#3]
The following test case

```
C casrot/3

{ [x] = 0; [zero] = 0; [one] = 1; [two] = 2;}

P0 (atomic_int *x, volatile int *zero)
{
        int r1 = atomic_compare_exchange_strong_explicit(x, zero, 1, memory_order_relaxed,
                                                                     memory_order_relaxed);
}

P1 (atomic_int *x, volatile int *one)
{
        int r2 = atomic_compare_exchange_strong_explicit(x, one, 2, memory_order_relaxed,
                                                                    memory_order_relaxed);
}

P2 (atomic_int *x, volatile int *two)
{
        int r3 = atomic_compare_exchange_strong_explicit(x, two, 3, memory_order_relaxed,
                                                                    memory_order_relaxed);
}

exists
(  zero=0 /\ one=1 /\ two=1 )
```

run with the empty cat model  

```
"empty" withinit
```

generates 3 executions, none of which satisfies the postcondition.

The execution where the CASes of P0 and P1 succeed and the CAS of P2 reads from the CAS of P0 (and fails) is, however, consistent (even taking the C++11 axioms into account).

**Comment by maranget** [comment]
Dear Victor,

Thanks for your report. I have no time to handle it now, but will do
as soon as possible.

All the best,


--Luc

**Comment by maranget** [comment]
Dear Victor,

The problem you reported should have been corrected by now in git hub version. The outcome (zero=0 /\ one=1 /\ two=1 ) is now allowed, both by your empty model (which already exists in the distribution as
`naked.cat` ) and by the c11 model.

Hence, `herd7 -c11 -model naked.cat V.litmus` now yields five outcomes.
