### ISSUE TITLE
diyone7 produces allowed tests

### ISSUE THREAD

**Issue by chacon01** [herd/herdtools7#323]
I've noticed that the diyone7 generator is producing tests with an "Allowed" condition. From what I can tell, they seem to involve `Amo.LdClr`/`Amo.StClr` which have no effect if the bit they are clearing is already 0.

For example, `diyone7` produces the following test for the cycle "DMB.SYdWR Amo.LdClr Rfe Amo.LdClr PodWWPL CoeLP":
```
AArch64 S+dmb.sy-amo.ldclr+amo.ldclr-popl
"DMB.SYdWR Amo.LdClr Rfe Amo.LdClr PodWWPL CoeLP"
Generator=diyone7 (version 7.56+02~dev)
Prefetch=0:x=F,0:y=W,1:y=F,1:x=W
Com=Rf Co
Orig=DMB.SYdWR Amo.LdClr Rfe Amo.LdClr PodWWPL CoeLP
{
0:X1=x; 0:X2=y;
1:X0=y; 1:X4=x;
}
 P0               | P1               ;
 MOV W0,#2        | MOV W2,#2        ;
 STR W0,[X1]      | LDCLR W2,W1,[X0] ;
 DMB SY           | MOV W3,#1        ;
 MOV W4,#1        | STLR W3,[X4]     ;
 LDCLR W4,W3,[X2] |                  ;
exists
([x]=2 /\ [y]=0 /\ 0:X3=0 /\ 1:X1=0)
```
This test is reported as "Allowed" by `herd7` because `[y]` is initially 0, both `LDCLR` instructions have no effect on the value of `[y]`:
```
Test S+dmb.sy-amo.ldclr+amo.ldclr-popl Allowed
States 2
0:X3=0; 1:X1=0; [x]=1; [y]=0;
0:X3=0; 1:X1=0; [x]=2; [y]=0;
Ok
Witnesses
Positive: 1 Negative: 2
Condition exists ([x]=2 /\ [y]=0 /\ 0:X3=0 /\ 1:X1=0)
Observation S+dmb.sy-amo.ldclr+amo.ldclr-popl Sometimes 1 2
Time S+dmb.sy-amo.ldclr+amo.ldclr-popl 0.03
Hash=8e867caf45dd964b145056a56b7c9dd7
```

**Comment by maranget** [comment]
Hi @chacon01. I think I see the problem, some allowed execution gives the same outcome as the forbidden one. Hence, one cannot identify the forbidden execution from the final condition of test. One potential solution would be use different initial values (here 3 or -1 for y). However , handling the general case in diy internals does not look straightforward. A workaround may be to use a few hand-edited tests for testing LDCLR.

A  slightly more automated solution may be to add a new option to diy that would define initial values for some variables. Then one may generate tests massively (_e.g._ with diy7), to identify the tests that are still allowed (with herd7) and to regenerate those with the new option (with diyone7 that accepts 'mcycle7' (standard) output as (standard) input). The process can be iterated with different initial values until stabilisation.

**Comment by chacon01** [comment]
Agree that a general solution would not be straightforward. I don't think we need a fix for this, especially since we can detect the allowed cases with `herd7` and that many microarchitectures have the same ordering logic for all the LD* and ST* Amo operations so we can effectively test ordering with "well behaved" Amo operations like LdAdd/StAdd.
