### ISSUE TITLE
diy7 produces allowed cycles with Hat

### ISSUE THREAD

**Issue by chacon01** [herd/herdtools7#324]
I'm observing some Allowed cycles being generated by `diy7`. They all seem to contain the `Hat` relaxation and have a "split" ordering on one of the threads such that the first effect is ordered before the last effect and the first effect is ordered before some intermediate effect but the intermediate effect isn't ordered before the last effect.

For example, with `-safe 'PodRRAP Hat Rfe' -relax '[DpAddrsW,PodWW]'`, `diy7` produces the cycle "PodRRAP Hat DpAddrsW PodWW RfePA" which corresponds to this test:
```
AArch64 RR+RW+poap+addrsW-po
"PodRRAP Hat DpAddrsW PodWW RfePA"
Generator=diyone7 (version 7.56+02~dev)
Prefetch=0:x=F,0:y=T,1:y=F,1:x=W
Com=Fr Rf
Orig=PodRRAP Hat DpAddrsW PodWW RfePA
{
0:X0=x; 0:X2=y;
1:X0=y; 1:X5=x;
}
 P0           | P1                  ;
 LDAR W1,[X0] | LDR W1,[X0]         ;
 LDR W3,[X2]  | EOR W2,W1,W1        ;
              | MOV W3,#1           ;
              | STR W3,[X0,W2,SXTW] ;
              | MOV W4,#1           ;
              | STR W4,[X5]         ;
exists
(0:X1=1 /\ 0:X3=0 /\ 1:X1=0)
```
On P0, the `LDAR` is barrier-ordered-before the `LDR`. On P1, the `LDR W1,[X0]` is dependency-ordered-before the `STR W3,[X0,W2,SXTW]` (by means of an address dependency) and the `LDR W1,[X0]` is dependency-ordered-before the `STR W4,[X5]` (which is a write in program order following an address dependency, or `addr; po; [W]`). However, there is no ordering between the `STR W3,[X0,W2,SXTW]` and the `STR W4,[X5]`.

In terms of the relaxations, `PodRRAP`, `Hat`, and `Rfe` all provide order and `[DpAddrsW,PodWW]` provides order between the first and last memory effect but not between the intermediate write and the last memory effect. To address this, I believe that communication (specifically `Hat`) must be between the first or last memory effect of a relaxation.

**Comment by maranget** [comment]
Hi @chacon01, I am lacking time for a deeper  analysis of the issue. For now I do not understand why you say that `Hat` provides order. Edge `Hat` was introduced to mean `read from the same (external, initial in practice) write. I did not see this as providing order, but I may be wrong. That said, your issue (as #323) is real, I am wondering whether it is worthwhile or not to aim at producing forbidden tests only from a set of `order providing` edges.

In effect, the current situation is that one can produce mostly forbidden sets from such edge sets and then filter out the allowed tests by running herd.

**Comment by chacon01** [comment]
Hi @maranget, thanks for the clarification. It looks like my understanding of the semantics of `Hat` weren't quite correct. My understanding was that `Hat` could be used in an unconstrained manner similar to how the other communication relaxations such as `Rfe`, `Fre`, or `Coe` can be.

It might be interesting to have a variant of `Hat` which ensured that an ordering between the two reads existed, but like you say, the issue I described can be handled easily enough with filtering.

**Comment by maranget** [comment]
I think the issue can be closed. Do not hesitate to re-open if I am wrong.
