### ISSUE TITLE
[herd-www] aarch64-MTE cat file looks to be out of date on web interface

### ISSUE THREAD

**Issue by benbancroft** [herd/herdtools7#338]
The aarch64-MTE.cat file provided by default for the aarch64-MTE profile includes an out of date cat file by default.

This is missing a couple of changes that went back into herd/libdir/aarch64.cat recently.

There may well be other profile cat files which are out of date, I have not personally checked.

This is resulting in the following MTE test showing as allowed, when it looks like it should actually be forbidden:

```
AArch64 Test
"Amo.LdEorAL PodWWLP CoePT DMB.SYdWRTQ HatQA"
Generator=diyone7 (version 7.56+02~dev)
Prefetch=0:x=F,0:y=W,1:y=F,1:x=T
Com=Co Fr
Orig=Amo.LdEorAL PodWWLP CoePT DMB.SYdWRTQ HatQA
{
0:X0=x:green; 0:X4=y:green;
1:X0=y:red; 1:X1=y:green; 1:X2=x:green;
}
 P0                 | P1            ;
 MOV W2,#1          | STG X0,[X1]   ;
 LDEORAL W2,W1,[X0] | DMB SY        ;
 MOV W3,#1          | LDAPR W3,[X2] ;
 STR W3,[X4]        |               ;
exists ([tag(y)]=:red /\ 0:X1=0 /\ 1:X3=0) /\ ~fault (P0,y)
```

**Comment by maranget** [comment]
Hi @benbancroft, thanks for reporting the problem. We are working on having the default AArch64 model to handle MTE. In other works getting rid of the specific aarch64-MTE cat file.

**Comment by maranget** [comment]
The web interface has been updated, aarch64-MTE default model being the standard aarch64.cat model.

Again, thanks for having reported the problem.
