### ISSUE TITLE
RC11 definition

### ISSUE THREAD

**Issue by hernanponcedeleon** [herd/herdtools7#377]
I'm trying to understand the following two definitions from [this file](https://github.com/herd/herdtools7/blob/master/herd/libdir/rc11.cat)
```
let myrmw = [RMW] | rmw
let rb = (rf^-1; mo) \ id
```
AFAIK herd models RMW instructions as a pair of events, however the definitions above suggest there might be cases where those instructions are modeled by a single event which is both a read and a write (otherwise the `\ id` would not make any sense).

**Comment by maranget** [comment]
Hi @hernanponcedeleon, the definition intends to handle both situations.

**Comment by hernanponcedeleon** [comment]
Thanks @maranget for the answer. Is there a concrete case where you model RMW as a single event? Can you point me to where this is being used?

**Comment by maranget** [comment]
As far as I can remember, herd generates RMW single events by default. You can try for instance `herd7 -conf c11 -cat rc11.cat -show all -evince` on the following test.
````
C SBA-ocaml

{}

P0 (atomic_int* y,atomic_int* x) {
   int r9 = atomic_exchange(x,1);
   int r0 = atomic_load(y);
}

P1 (atomic_int* y,atomic_int* x) {
   int r9 = atomic_exchange(y,1);
   int r0 = atomic_load(x);
}

exists (0:r0=0 /\ 1:r0=0)

````

**Comment by hernanponcedeleon** [comment]
This clarifies my doubt. Thanks @maranget!
