### ISSUE TITLE
Commands of herdtools7 7.56.1 doesn't print ther version

### ISSUE THREAD

**Issue by akiyks** [herd/herdtools7#378]
After installing herdtools7 by `opam install`, running `herd7 -version` prints only:
```
, Rev: exported
```

Looking at commit f544fd4f8d27, I suspect fields of `name: "herdtools7"` and
`version: "7.56.1"` were removed by accident.

Can you do another release with this issue fixed?
I have no idea if it can be `7.56.1` or needs to be `7.56.2`.

**Comment by maranget** [comment]
Ah, I have removed this line following a suggestion by spam maintainer.  Of course, the line was used for building the version message.

If you don’t mind I’d rather release a 7.56.2 version.

**Comment by akiyks** [comment]
`7.56.2` works for me.

**Comment by maranget** [comment]
Release `7.56.2` is now published, `opam` package has been accepted.

Thanks again for your repoorts.

**Comment by akiyks** [comment]
Now I've got `7.56.2` through `opam` commands.
Closing this issue.

Thanks!
