### ISSUE TITLE
Failed atomic_cmpxchg_acquire interpreted as R[once]

### ISSUE THREAD

**Issue by hernanponcedeleon** [herd/herdtools7#384]
I'm trying the following litmus tests in the [web-version](http://diy.inria.fr/www/#) of `herd7`
```
C C-atomic-cmpxchg-failure-02

{
  atomic_t x = ATOMIC_INIT(0);
  atomic_t z = ATOMIC_INIT(0);
}

P0(atomic_t *x, atomic_t *z) {
  int r0; int r1;
  r0 = atomic_cmpxchg_acquire(z,2,1);
  r1 = atomic_read(x);
}

P1(atomic_t *x, atomic_t *z) {
  atomic_set(x,1);
  atomic_set_release(z,1);
}

exists (0:r0 = 1 /\ 0:r1 = 0)
```
This is what I observe in the event structures section
<img width="478" alt="Screenshot 2022-05-20 at 13 51 22" src="https://user-images.githubusercontent.com/11671435/169523179-78553981-7615-4378-a402-21abff817291.png">
meaning that the read part of the comparison is given `once` as memory order. I checked the code and I assume this is coming [from here](https://github.com/herd/herdtools7/blob/09cd29e2b6f1d98c0254fd50b66739ddf2974f15/herd/CSem.ml#L110). The question is: why the read part of an `cmpxhg_acquire` is assigned `once` instead of `acquire`?

**Comment by maranget** [comment]
It looks like a bug. Thanks for reporting it.

**Comment by maranget** [comment]
Ok, I have just checked semantics as described informally for instance [here, line 1803](https://kernel.googlesource.com/pub/scm/linux/kernel/git/rw/ubifs/+/refs/heads/fixes/tools/memory-model/Documentation/explanation.txt);

> [..] (the read part of the cmpxchg operation acts as an acquire fence only if the operation is successful) [...]

Hence it seems that herd implements the semantical intent.

**Comment by hernanponcedeleon** [comment]
Yes, I also found that the [kernel documentation](https://github.com/torvalds/linux/blob/master/tools/memory-model/Documentation/ordering.txt) says
>Note that conditional RMW atomic operations such as cmpxchg() are only guaranteed to provide ordering when they succeed.

But for the failure mode I would still assume `relaxed` should be the correct ordering and not `once`.

**Comment by maranget** [comment]
There is no `relaxed` in the kernel memory model. The file [linux-bernel.bell](https://github.com/torvalds/linux/blob/master/tools/memory-model/linux-kernel.bell) list all legal annotations.

> instructions R[{'once,'acquire,'noreturn}]
instructions W[{'once,'release}]
instructions RMW[{'once,'acquire,'release}]

Events annotated by `_annot_ make up the set _Annot_, which set can be referenced to in the cat file. Hence, there is a `Once` set of memory events but no set `Relaxed`.
