### ISSUE TITLE
herd7: exists clause that should be prohibited is now allowed

### ISSUE THREAD

**Issue by akiyks** [herd/herdtools7#433]
Hi,

Recent commit c768fc5f06e5 affected a litmus test from perfbook's CodeSamples.

```
C Lock-outside-across

{}

P0(int *x, int *y, spinlock_t *sp)
{
	int r1;

	WRITE_ONCE(*x, 1);
	spin_lock(sp);
	r1 = READ_ONCE(*y);
	spin_unlock(sp);
}

P1(int *x, int *y, spinlock_t *sp)
{
	int r1;

	spin_lock(sp);
	WRITE_ONCE(*y, 1);
	spin_unlock(sp);
	r1 = READ_ONCE(*x);
}

exists (0:r1=0 /\ 1:r1=0)
```
With herd7 7.56.2 and master branch up until commit f6de67116f5b, this litmus test
results in "Never" (in combination of linux-kernel.cfg of LKMM).
Commit c768fc5f06e5 changed the result to "Sometimes".

Can you look into this?

Note: -optace option is not specified.

**Comment by maranget** [comment]
Hi @akiyks, I am working on it. Sorry for the inconvenience and thanks for your report.

**Comment by maranget** [comment]
Fixed by PR #435. Thanks again for reporting the problem

**Comment by akiyks** [comment]
Hi @maranget,

Thank you for the quick fix. Now I see the expected result.

Closing this issue now.

**Comment by akiyks** [comment]
Hi @maranget,

At current master d6fcd729dd53, I see this issue resurfaced.
Bisection points commit 3a2524d3da27 as the first bad commit.
Can you look into this again?

**Comment by maranget** [comment]
Hi @akiyks, PR #459, now merged in master, should fix this problem. Sorry for any inconvenience and thanks a lot for noticing and reporting so swiftly.

**Comment by akiyks** [comment]
@maranget Thanks!
Tested the fix and got the expected result.

Closing again.
