### ISSUE TITLE
dump all execution graphs

### ISSUE THREAD

**Issue by sohachak** [herd/herdtools7#443]
Hi,

Is it possible to dump all the execution graphs explored by herd? 

I tried the following command, but it does not provide all the execution graphs. 

% herd7 -show prop -gv MP.litmus 

Please suggest if this is possible.

Best regards,

**Comment by maranget** [comment]
Try
```
% herd7 -show all -gv MP.litmus
```
You can also look at the manual that provides a [short description of most `herd7` command line options](https://diy.inria.fr/doc/herd.html#sec121).

**Comment by sohachak** [comment]
Thank you for your response! I get the following output, but no dump of the execution graphs with all the relations. 
More specifically, I am interested in running the C11 examples (e.g. in catalogue/c11popl15/tests/illustrative) 

mytests % herd7 -show all -gv MP.litmus
Test MP Allowed
States 4
1:X0=0; 1:X2=0;
1:X0=0; 1:X2=1;
1:X0=1; 1:X2=0;
1:X0=1; 1:X2=1;
Ok
Witnesses
Positive: 1 Negative: 3
Condition exists (1:X0=1 /\ 1:X2=0)
Observation MP Sometimes 1 3
Time MP 0.01
Hash=211d5b298572012a0869d4ded6a40b7f

**Comment by sohachak** [comment]
Success! The following command dumped all the executions in the .dot file.

herd7 -show all -gv -o ./ MP.litmus

**Comment by maranget** [comment]
I am glad you found the answer. If documentation is unclear or if you think that it should be more exhaustive, do not hesitate to submit a detailed issue.

**Comment by maranget** [comment]
I think the issue can be closed, if no objection.

**Comment by sohachak** [comment]
Belated reply. Thank you again for your timely response!
