### ISSUE TITLE
Unusual result of litmus testing on SC 

### ISSUE THREAD

**Issue by jaag5678** [herd/herdtools7#53]
Hi there,

I just started using herd7 tool  to try out some examples given in the documentation (http://diy.inria.fr/doc/herd.html). 

But on trying out the example of store buffering (SB.litmus) for Sequential Consistency, I am not getting the output as No Positive Witnesses . I have used the files provided in the documentation itself of the model and the litmus test. 

Here is what I got.
![image](https://user-images.githubusercontent.com/14888184/93148525-03704880-f6c2-11ea-9a35-ae80b35ae7d9.png)

Here is the sc.cat file which I downloaded from the documentation link. 
![image](https://user-images.githubusercontent.com/14888184/93148623-4a5e3e00-f6c2-11ea-8ffb-48c4d46979bb.png)

I also tried it for a simple message passing example.  But I am not getting the intended output of No Positive Witness. 

Am I missing something here? Or have I misunderstood the output. 

Thank you,
Sincerely,
jaag5678

**Comment by maranget** [comment]
Hi,

The bahaviour you observe is not normal.

It may be due to a mismatch between your herd7 binaries and the sc.cat model you got from documentation.

--Luc

**Comment by maranget** [comment]
Issue close to be closed.
