### ISSUE TITLE
make：***No rule to make target 'all'. Stop

### ISSUE THREAD

**Issue by Ricky-hub-learning** [herd/herdtools7#546]
I use ubuntu to install herdtools7
I have installed herdtools7,OCaml,dune,and menhir
However, when I have been trying "make all" ,I keep getting the error "make: *** No rule to make target 'all'.Stop"
maybe my $home is wrong?
I check"**_Tools will be installed in PREFIX/bin, and various files in PREFIX/share/herdtools7. By default (see Makefile) PREFIX is $HOME._**"and I found my $HOME maybe "/home/lok/.opam/default" but it is still not work
what can I do?

**Comment by maranget** [comment]
Hi @Ricky-hub-learning. It seems that you attempt to compile herdtools7 from sources. Maybe it will be more convenient to use the opam installation. Provided opam is installed on your system, installing herdtools7 is as simple as:
```
% opam install herdtools7
```
Then the tools are accessible from the command line (provided opam is completely installed). You can try:
```
% diyone7 -arch AArch64 PodWW Rfe PodRR Fre
...
```

**Comment by Ricky-hub-learning** [comment]
Amazing！Thank you!
