### ISSUE TITLE
A potential mistake in diy7 documentation

### ISSUE THREAD

**Issue by DehengYang** [herd/herdtools7#555]
Dear @maranget ,

Sorry for interrupting here with such a small issue.

I noticed that in Section 11.5 (Usage of diy7) of **A diy “ Seven ” tutorial**, it writes:

> "3. If the option -cumul false is specified, diy7 will not construct the sequence of Rfe followed by a fence (or B-cumulativity) candidate relaxation or of a fence (or A-cumulativity) candidate relaxation followed by Rfe."

If I do not misunderstand [1], Rfe followed by a fence (i.e.,  Rfe; fence) refers to **A-cumulativity** rather than **B-cumulativity**.  Similarly, fence followed by Rfe (i.e.,  fence; Rfe) refers to **B-cumulativity** rather than **A-cumulativity**.  As I am not 100% sure about this, I choose to create an issue than a PR. Please kindly advise. Thank you!

[1] Jade Alglave, Luc Maranget, Michael Tautschnig: Herding Cats: Modelling, Simulation, Testing, and Data Mining for Weak Memory. ACM Trans. Program. Lang. Syst. 36(2): 7:1-7:74 (2014)

Yours sincerely,
Deheng

**Comment by maranget** [comment]
You are right. Thank you for your attentive reading.
