### ISSUE TITLE
Illegal operation mask32 on x:green

### ISSUE THREAD

**Issue by hugookeeffe** [herd/herdtools7#565]
We are encountering the following Warning message with the following test:
Warning message:
`Warning: File "Armv8-mte+atomics-ext-forbidden338.litmus": Illegal operation mask32 on x:green (User error)`
Litmus test
```
AArch64 Armv8-mte+atomics-ext-forbidden338
"DpAddrdRTA Amo.CasAL PodWWLP RfePT HatTT"
Cycle=RfePT HatTT DpAddrdRTA Amo.CasAL PodWWLP
Relax=T
Safe=Hat Rfe DpAddrdR [Amo.CasAL,PodWW]
Generator=diy7 (version 7.56+02~dev)
Com=Rf Rf
Orig=DpAddrdRTA Amo.CasAL PodWWLP RfePT HatTT
{
0:X1=x:green; 0:X3=y:green;
1:X1=x:green;
}
P0               | P1         ;
MOV X0,X1        | MOV X0,X1  ;
LDG X0,[X1]      | LDG X0,[X1] ;
EOR W2,W0,W0     |            ;
ADD X4,X3,W2,SXTW |            ;
MOV W5,#0        |            ;
MOV W6,#1        |            ;
CASAL W5,W6,[X4] |            ;
MOV W7,#1        |            ;
STR W7,[X1]      |            ;
exists (0:X0=x:green /\ 0:X5=0 /\ 1:X0=x:green)
```
The issue seems to be that we are adding a mask to a symbolic value. In our case, we are using W, which applies a mask, meaning that our EOR operation fails.

We think we could fix this either in herd7 by adding a check before mask to see if the two variables are the same for eor, or it could be fixed in diy7 by using X instead of W when doing an eor on two tag values. However we are unsure what solution is better and what other possible implications this could have.

**Comment by relokin** [comment]
The minimal tests that show the problem are the following:

```
AArch64 xor-symb
{
  int x;
  int *p = &x;
  0:X0=p;
}

 P0           ;
 EOR X1,X0,X0 ;
locations[0:X1]
```
where
```
$> herd7 xor-symb.litmus
Test xor-symb Required
States 1
0:X1=0;
Ok
Witnesses
Positive: 1 Negative: 0
Condition forall (true)
Observation xor-symb Always 1 0
Time xor-symb 0.00
Hash=ba27ab95b67d4c9ff0b109502e5bcd20
```

but when we the `EOR` operates on the 32bit registers:

```
AArch64 xor-symb-mask32
{
  int x;
  int *p = &x;
  int 0:X0=p;
}

 P0           ;
 EOR W1,W0,W0 ;
locations[0:X1]
```

 herd7 gives up:

```
$> herd7 xor-symb-mask32.litmus
Warning: File "xor-symb-mask32.litmus": Illegal operation mask32 on p (User error)
```

but litmus7 can execute this and indeed it gives the expected result:
```
Test xor-symb-mask32 Required
Histogram (1 states)
1000000:>0:X1=0;
Ok

Witnesses
Positive: 1000000, Negative: 0
Condition forall (true) is validated
Hash=0611befa56d5cbc809cc27fe562bebc1
Observation xor-symb-mask32 Always 1000000 0
Time xor-symb-mask32 0.02
```

As Hugo's MTE test, the outcome of the EOR can be useful in tests where we want to create an address dependency. Currently this test:

```
AArch64 addr-symb
{
  int x;
  int y = 1;
  int *p = &x;
  0:X0=p;
  0:X4=y;
}

 P0             ;
 LDR X1,[X0]    ;
 EOR X2,X1,X1   ;
 LDR W3,[X4,X2] ;
locations[0:X3]
```

Can be run with herd7

```
$> herd7 addr-symb.litmus
Test addr-symb Required
States 1
0:X3=1;
Ok
Witnesses
Positive: 1 Negative: 0
Condition forall (true)
Observation addr-symb Always 1 0
Time addr-symb 0.01
Hash=99858dc9f4f456f864ec3a5c2f5db7a1
```

whereas when we use 32bit registers:

```
AArch64 addr-symb-mask32
{
  int x;
  int y = 1;
  int *p = &x;
  0:X0=p;
  0:X4=y;
}

 P0                  ;
 LDR W1,[X0]         ;
 EOR W2,W1,W1        ;
 LDR W3,[X4,W2,SXTW] ;
locations[0:X3]
```

the test fails

```
$> herd7 addr-symb-mask32.litmus
Warning: File "addr-symb-mask32.litmus": Illegal operation mask32 on x (User error)
```

**Comment by maranget** [comment]
The root cause of the problem attempting loading an address into a W register, as illustrated by the following, even shorter example:
```
AArch64 load-x-as-w
{
int x=1;
int *p = &x;
0:X0=p;
}
  P0        ;
LDR W1,[X0] ;
locations [0:X1;]
```
We have:
```
% herd7 load-x-as-w.litmus 
Warning: File "load-x-as-w.litmus": Illegal operation mask32 on x (User error)
```
Do we really need this to work?

**Comment by maranget** [comment]
Reading the previous examples, the most simple fix would probably to add a particular case to EOR. Fixing dit is also an option.

**Comment by relokin** [comment]
> The root cause of the problem is attempting loading an address into a W register, as illustrated by the following, even shorter example:
> 
> ```
> AArch64 load-x-as-w
> {
> int x=1;
> int *p = &x;
> 0:X0=p;
> }
>   P0        ;
> LDR W1,[X0] ;
> locations [0:X1;]
> ```
> 
> We have:
> 
> ```
> % herd7 load-x-as-w.litmus 
> Warning: File "load-x-as-w.litmus": Illegal operation mask32 on x (User error)
> ```
> 
> Do we really need this to work?

For `load-x-as-w`, I think we can't get it to work because we're asking for the 32 bit of a symbolic value. But in `xor-symb` we're going one step further and we now that we xor the same value so it might be possible to return the result. There are some logical operators (e.g., x xor x, x && 0, x || 1) - also some arithmetic (x - x, x * 0, x / x), that it might be possible to compute in herd7.

**Comment by relokin** [comment]
But @maranget, this is what we want to get your opinion on is: is it worth fixing this in herd7 or should we fix diy7 and avoid generating such tests?

**Comment by maranget** [comment]
My first idea would be  a fix attempt of diy. For instance generate the EOR on the X register looks reasonable. 

The computation for an address dependency should be something like:
```
LDR X0,[X1]
EOR X2,X0,X2
ADD X4,X3,X2
```

**Comment by maranget** [comment]
That said, adding a specfic rule xor(v,v) -> 0 for all v would  not hurt.

**Comment by maranget** [comment]
Hi, PR #571 is a fix attempt. If you could check that the fix suffices... Namely I found and fixed several occurrences of the W vs. X problem. Maybe some remain and extensive testing would help. I am off until May 2.

**Comment by hugookeeffe** [comment]
after checking the fix, it seems to fix our problem. Thank you for the help! If @relokin is also ok with it, I can close this issue

**Comment by maranget** [comment]
> I am off until May 2.

Well I was off until May 12... I merge PR #571 now. I let you decide to close this issue, if appropriate.

**Comment by relokin** [comment]
@hugookeeffe now that PR #571 has been merged, should we close this issue as well?

**Comment by hugookeeffe** [comment]
yes @relokin , sounds good, I will close this issue. thank you @maranget !
