### ISSUE TITLE
Report of a potential bug related to RISC-V aqrl format

### ISSUE THREAD

**Issue by DehengYang** [herd/herdtools7#581]
Hi,

I observed a potential bug in herd project, the steps to reproduce the failure is as follows:

1. create `X.conf` and write:

```powershell
-arch RISCV
-safe Pod**,Rfe,Wse,Fre,Rfi
-relax Aq,Rl,AR
-size 4
-nprocs 2
-num false
-sufname +NEW
-variant ConstsInInit
-variant AsAmo
```

2. create litmus tests, run:

```powershell
mkdir -p TMP1
mkdir -p TMP2
diy7 -conf X.conf -cond observe -o TMP1
herd7 -model uniproc.cat TMP1/@all > U
mlog2cond7 -forall true -optcond true < U > conds.txt
recond7 -toexists true -conds conds.txt -o TMP2 TMP1/@all
```

3. run a litmus test:

```powershell
cd TMP2
herd7 SB+po+poarp+NEW.litmus
```

Unexpectedly, there is no simulation output. The output is:

> Warning: File "SB+po+poarp+NEW.litmus", line 15, characters 30-32: unexpected 'x0' (in prog) (User error)

The corresponding `SB+po+poarp+NEW.litmus` code is:

```powershell
RISCV SB+po+poarp+NEW
"PodWR FrePAR PodWRARP Fre"
Cycle=Fre PodWR FrePAR PodWRARP
Relax=AR
Safe=Fre PodWR
Generator=diy7 (version 7.56+03)
Prefetch=0:x=F,0:y=T,1:y=F,1:x=T
Com=Fr Fr
Orig=PodWR FrePAR PodWRARP Fre
{
0:x5=1; 0:x6=x; 0:x8=y;
1:x5=1; 1:x6=y; 1:x8=x;
}
 P0          | P1                        ;
 sw x5,0(x6) | amoswap.w.aqrl x0,x5,(x6) ;
 lw x7,0(x8) | lw x7,0(x8)               ;
locations [x; y; 0:x7; 1:x7;]
exists (true)
```

After several attempts, I noticed that if I change `amoswap.w.aqrl` into `amoswap.w.aq.rl`, the herd7 will work:

> apr@apr:~/apr/TMP2$ herd7 SB+po+poarp+NEW.litmus
> Test SB+po+poarp+NEW Allowed
> States 4
> 0:x7=0; 1:x7=0; [x]=1; [y]=1;
> 0:x7=0; 1:x7=1; [x]=1; [y]=1;
> 0:x7=1; 1:x7=0; [x]=1; [y]=1;
> 0:x7=1; 1:x7=1; [x]=1; [y]=1;
> Ok
> Witnesses
> Positive: 4 Negative: 0
> Condition exists (true)
> Observation SB+po+poarp+NEW Always 4 0
> Time SB+po+poarp+NEW 0.00
> Hash=8962583f355a03e4150595abf1929204

Accordingly, to fix this bug, we may modify: https://github.com/herd/herdtools7/blob/4e1a0d1fd675e6613d67484153b7e2d39df1537d/lib/RISCVBase.ml#L273 into:

```powershell
  | AcqRel -> ".aq.rl"
```

But I used `git blame` and observed that https://github.com/herd/herdtools7/commit/fb06763a62941ab4e29a7b18bab1b1db922e3921 remove the `.` intentionally. Therefore, I am not sure about this issue and report it here for your consideration. Thank you.

Yours sincerely,

Deheng

**Comment by maranget** [comment]
Thanks for your report. If they are right, the comments from PR #376 confirm that commit fb06763 is adequate. I guess that parsing should also be corrected. Will check.

**Comment by maranget** [comment]
PR #582 is a fix attempt.

**Comment by DehengYang** [comment]
Thank you very much for the prompt fix. That looks great to me!

**Comment by DehengYang** [comment]
Thank you very much for the fix, this is really a great project!
