### ISSUE TITLE
About the equivalence of the two CAT models for RISC-V

### ISSUE THREAD

**Issue by DehengYang** [herd/herdtools7#600]
Dear Prof. Maranget,

Sorry for disturbing you with this letter.

I have noticed that the RISC-V ISA manual presents two Herd CAT models for the RISC-V memory model (i.e., RVWMO):

> Memory models are written in the domain specific language Cat. This section provides two Cat memory model of RVWMO. The first model, Figure B.7, follows the global memory order, Chapter 14, definition of RVWMO, as much as is possible for a Cat model. The second model, Figure B.8, is **an equivalent, more efficient, partial order** based RVWMO model.

The first model refers to [https://github.com/herd/herdtools7/blob/master/herd/libdir/riscv-total.cat](https://github.com/herd/herdtools7/blob/master/herd/libdir/riscv-total.cat), and the second model refers to [https://github.com/herd/herdtools7/blob/master/herd/libdir/riscv.cat](https://github.com/herd/herdtools7/blob/master/herd/libdir/riscv.cat). 

I am confused about the statement _"The second model, Figure B.8, is **an equivalent, more efficient, partial order** based RVWMO model"_ without explanations or proofs. I cannot figure out why the second model is equivalent to the first one, while their definitions in the CAT files are very different. **It would be sincerely appreciated if any references or guidance could be provided about the equivalence between the two models.** Thank you!

Thank you in advance for your time and help.

Yours sincerely,
Deheng

**Comment by maranget** [comment]
Hi @DehengYang. I am afraid we have no precise proof for this equivalence. It should be very similar to the equivalence proof of some ARMv8  models from the paper [_"Armed Cats: formal concurrency modelling at Arm"_](https://inria.hal.science/hal-03470858). More specifically you can have a look at the equivalence of the ARMv8 standard model (Section 4) and of the models of Section 6. Proof has been verified with the Coq proof assistant and is sketched in section 7.

One of the difficulty of the proof is  the TSO style of the rf relation. The proof for SC is simpler it is sketched in the slides of course 03 [here](http://pauillac.inria.fr/~maranget/MPRI/index.html) (from slide 17).

**Comment by DehengYang** [comment]
Dear Prof. @maranget ,

Thank you very much for the detailed explanation and guidance. That extremely helps! I will carefully read the paper and learn the valuable slides you kindly released to get a better understanding of weak memory models. 

Thank you again for the great help and wish you a nice week!

Yours sincerely,
Deheng
