### ISSUE TITLE
[aarch64] cacheability attribute regions fail to parse

### ISSUE THREAD

**Issue by gonzalobg** [herd/herdtools7#654]
The example in this blog [blog](https://community.arm.com/arm-community-blogs/b/architectures-and-processors-blog/posts/expanding-memory-model-tools-system-level-architecture):

```
AArch64 mp-xWB-yWT
{
0 :X1=x ; 0 :X3=y ;
1 :X1=y ; 1 :X3=x ;
}
P0          | P1          ;
MOV W0,#1   | LDR W0,[X1] ;
STR W0,[X1] | LDR W2,[X3] ;
MOV W2,#1   |             ;
STR W2,[X3] |             ;
regions: x: normal inner-write-back outer-write-back, y: normal inner-write-through outer-write-through
exists (1:X0=1 /\ 1:X2=0)
```

when generated as follows, fails with the following error:

```
$ ~/bin/litmus7 -mach kvm-aarch64 -variant fatal -o out.tar blog.litmus
File "blog.litmus" File "blog.litmus", line 11, character 24: Lex error AArch64 lexer (in prog)
```

Line 11 character 24 corresponds to the following line and highlighted character:

```
regions: x: normal inner-write-back outer-write-back, y ...
                        ^
```

That is, something fails to parse at the `-` after the first `inner-`

I looked at the examples in the repository but the only example I was able to find using `regions` is [this one](https://github.com/herd/herdtools7/blob/a837761b389b2cf7dbfb3ff85d9e387e5d3fbd5c/herd/tests/instructions/C/C12.litmus#L8). The older KVM branch had some more examples of regions for HSA, but nothing with a `-` in the region name.

The source code shows that the variable names are `PTEInner-....` , but trying to use those names in the litmus tests fails as well.

**Comment by relokin** [comment]
The syntax of the litmus has changed since we wrote this blog. We use the `PTE` tuple to set the memory attributes much like how it would be done in software. So the test above would be written as:

```
AArch64 mp-xWB-yWT
{
 [PTE(y)]=(attrs:(Inner-write-through,Outer-write-through));
 [PTE(x)]=(attrs:(Inner-write-back,Outer-write-back));
 0 :X1=x ; 0 :X3=y ;
 1 :X1=y ; 1 :X3=x ;
}
 P0          | P1          ;
 MOV W0,#1   | LDR W0,[X1] ;
 STR W0,[X1] | LDR W2,[X3] ;
 MOV W2,#1   |             ;
 STR W2,[X3] |             ;
exists (1:X0=1 /\ 1:X2=0)
```

Note though that if you run this a KVM payload or any other hypervisor, the memory attributes of stage2 translation would have an impact on the observable executions of this program.

**Comment by gonzalobg** [comment]
Thank you Nikos. Closing the issue.

Do you know if there is a way to create two different aliases to the same memory location?
