### ISSUE TITLE
herd7 cant recognize the general register of RISCV in standard litmus file

### ISSUE THREAD

**Issue by N1neSun** [herd/herdtools7#742]
![787a3092adb7ff8d00a77352920c573](https://github.com/herd/herdtools7/assets/13716571/0917226a-c5ef-44a8-9cf2-e22c022deb6e)
![5c910a5f6673a85d1ac79e66c50ea66](https://github.com/herd/herdtools7/assets/13716571/9e6feeb1-2b0f-477a-8dc6-c9eb1ba73323)
A02.litmus is generated by litmus7,but run it by herd7 will cause error.

**Comment by maranget** [comment]
Hi @N1neSun,  thanks for your bug report.

You are apparently using the opam version. Notice that herdtools7 head version is exempt from this very annoying bug.

Hence, we can advise you to recompile herdools7 from head sources, which is relatively [simple]( https://github.com/herd/herdtools7/blob/master/INSTALL.md) once you have opam installed.

**Comment by N1neSun** [comment]
Thank you very much for the above method helping me solve the problem. btw, I wish you a happy weekend and a Merry Christmas in advance.
