### ISSUE TITLE
diy: missing existence condition with Pos

### ISSUE THREAD

**Issue by ambroise-arm** [herd/herdtools7#79]
Observed on version 7.56+02

With the following litmus test:
```
AArch64 A
Orig=PodWW Rfe PodRR PosRR Fre
{
0:X1=x; 0:X3=y;
1:X1=y; 1:X3=x;
}
 P0          | P1          ;
 MOV W0,#1   | LDR W0,[X1] ;
 STR W0,[X1] | LDR W2,[X3] ;
 MOV W2,#1   | LDR W4,[X3] ;
 STR W2,[X3] |             ;
exists (1:X0=1 /\ 1:X4=0)
```

The state of `1:X2` (expected to be 0) doesn't appear in the existence condition, probably because the two reads resulting in `1:X2` and `1:X4` are from the same memory location. I think it should be there, because the values read can be different.

It also shows with `-variant memtag`, even when reading from different banks:
```
AArch64 B
Orig=PodWWTT RfeTT PodRRTT PosRRTP FrePT
{
0:X0=x:red; 0:X1=x:green; 0:X2=y:red; 0:X3=y:green;
1:X1=y:red; 1:X3=x:green;
}
 P0          | P1          ;
 STG X0,[X1] | MOV X0,X1   ;
 STG X2,[X3] | LDG X0,[X1] ;
             | MOV X2,X3   ;
             | LDG X2,[X3] ;
             | LDR W4,[X3] ;
exists (1:X0=y:red /\ 1:X4=0) /\ ~fault(P1,x)
```

**Comment by maranget** [comment]
Option `-nooptcond` will produce a test with  a (much) larger existence condition. However default behaviour may in effect include both reads at the end of a PosRR edge. This can be done easily. Thanks.

See commit 248cd0aee6a4f0b9dfe9b7728d61cda2d5ff65fd
