### ISSUE TITLE
Herd does not build with OCamlbuild

### ISSUE THREAD

**Issue by eth-arm** [herd/herdtools7#98]
PR #84 introduced a new library dependency, [Stdint](https://github.com/herd/herdtools7/blob/1fd2e73e1e690ddc315c47f54501bfbdd4891ce2/lib/dune#L30). The OCamlbuild script was not updated to match, and now Herd does not build with OCamlbuild.

**Comment by maranget** [comment]
Issue hopefully solved by adding [Stdint dependency](https://github.com/herd/herdtools7/blob/48660e7986c78a3fac270d13c86588b9be82fd2c/_tags#L17) for ocamlbuild. Unfortunately, adopted solution  adds another dependency on [ocamlfind](https://github.com/herd/herdtools7/blob/48660e7986c78a3fac270d13c86588b9be82fd2c/ocb-build.sh#L27). In fact I still need ocamlbuild for two reasons:

1. I sometimes (not that often) need exception traces. I get them by running the debug byte code executables, which I build easily with `ocamlbuild herd/herd.d.byte`.
2. The web interface (directory herd-www) still relies on ocamlbuild for its build process.

I'd be happy to say goodbye to ocamlbuild if someone would find a way to perform tasks  1. and 2. without ocamlbuild.

**Comment by jalglave** [comment]
Solved by https://github.com/herd/herdtools7/commit/48660e7986c78a3fac270d13c86588b9be82fd2c
